---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: "v1.21.1"
      helm:
        valueFiles:
          - $back-repo/cert-manager/values.yaml
    - repoURL: https://github.com/Abeehiltz/k8s-deployment
      path: cert-manager
      targetRevision: HEAD
      ref: back-repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      enabled: false
      prune: true
