---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
      path: .
      targetRevision: "0.71.1"
      helm:
        valueFiles:
          - $back-repo/monitoring/values.yaml
    - repoURL: oci://ghcr.io/grafana/helm-charts/grafana-operator
      path: .
      targetRevision: "5.22.0"
      helm:
        valueFiles:
          - $back-repo/monitoring/values-grafana-operator.yaml
    - repoURL: https://github.com/Abeehiltz/k8s-deployment
      path: monitoring
      targetRevision: HEAD
      ref: back-repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      enabled: false
      prune: true
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - kind: Secret
      namespace: monitoring
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
